#!/usr/bin/env python3
"""
ADR Generator — converts raw content to Architecture Decision Records.

Follows adr-maintainer skill structure exactly:
- docs/NNNN-title-slug.md in MADR 4.0.0 format
- Fields: id, title, status, date, authors, domain, level, confidence
- Sections: Context, Decision, Consequences
"""

import re
from pathlib import Path
from datetime import datetime


class ADRGenerator:
    
    ADR_DIR = Path.home() / ".openclaw/workspace-genesis/docs/adrs"
    
    def __init__(self, adr_path=None):
        self.adr_dir = Path(adr_path) if adr_path else self.ADR_DIR
    
    def generate(self, raw_content):
        """
        Generate ADR from raw content.
        Returns list of created file paths.
        """
        files_created = []
        
        # Clean content
        content = self._clean_content(raw_content)
        
        # Determine next number
        next_num = self._get_next_number()
        
        # Extract title from content
        title = self._extract_title(content)
        slug = self._title_to_slug(title)
        
        # Create ADR file
        adr_file = self._create_adr(next_num, title, slug, content)
        if adr_file:
            files_created.append(adr_file)
        
        return files_created
    
    def _clean_content(self, content):
        """Strip HTML, normalize whitespace."""
        text = re.sub(r'<[^>]+>', ' ', content)
        text = re.sub(r'\s+', ' ', text).strip()
        if len(text) > 40000:
            text = text[:40000] + "\n\n[... truncated ...]"
        return text
    
    def _get_next_number(self):
        """Get next sequential ADR number."""
        if not self.adr_dir.exists():
            self.adr_dir.mkdir(parents=True, exist_ok=True)
            return 1
        
        files = list(self.adr_dir.glob("[0-9]*.md"))
        nums = []
        for f in files:
            try:
                nums.append(int(f.name.split("-")[0]))
            except ValueError:
                pass
        
        return (max(nums) + 1) if nums else 1
    
    def _extract_title(self, content):
        """Extract ADR title from content."""
        lines = content.split("\n")
        for line in lines:
            line = line.strip()
            if len(line) > 10:
                # Remove common prefixes
                line = re.sub(r'^(feature|scenario|given|when|then|#)\s*', '', line, flags=re.IGNORECASE)
                if line:
                    return line[:100]
        return "ADR: Gherkin Pipeline Generated Decision"
    
    def _title_to_slug(self, title):
        """Convert title to URL-safe slug."""
        slug = re.sub(r'[^a-zA-Z0-9\s-]', '', title)
        slug = re.sub(r'\s+', '-', slug).lower().strip("-")
        return slug[:60] or "decision"
    
    def _create_adr(self, num, title, slug, content):
        """Create ADR file in MADR 4.0.0 format."""
        self.adr_dir.mkdir(parents=True, exist_ok=True)
        
        num_str = str(num).zfill(4)
        filename = f"{num_str}-{slug}.md"
        filepath = self.adr_dir / filename
        
        # Extract context, decision, consequences from content
        context = self._extract_section(content, ["context", "background", "given"])
        decision = self._extract_section(content, ["decision", "when", "action", "then"])
        consequences = self._extract_section(content, ["consequence", "result", "outcome", "effect"])
        
        adr_content = f"""---
id: adr.{num_str}
pageType: adr
title: "ADR {num_str} — {title}"
status: proposed
date: "{datetime.now().strftime('%Y-%m-%d')}"
authors: Genesis via Gherkin Pipeline
domain: specification
level: feature
confidence: 0.75
updatedAt: "{datetime.now().strftime('%Y-%m-%d')}"
tags:
  - gherkin
  - bdd
  - specification
  - pipeline
sourceIds: []
relatedConcepts:
  - concept:gherkin-guidelines
  - concept:living-documentation
---

# ADR {num_str} — {title}

## Status
Proposed

## Context

{context}

## Decision

{decision}

## Consequences

{consequences}

## Metadata

- Generated by: Gherkin Spec Pipeline
- Source type: gherkin-pipeline
- Format: MADR 4.0.0
"""
        
        try:
            filepath.write_text(adr_content, encoding="utf-8")
            return filepath
        except Exception as e:
            print(f"    [!] ADR write failed: {e}")
            return None
    
    def _extract_section(self, content, keywords):
        """Extract a section based on keywords."""
        lines = content.split("\n")
        section_lines = []
        capture = False
        
        for line in lines:
            stripped = line.strip().lower()
            
            # Check for section headers
            for kw in keywords:
                if stripped.startswith(kw) or stripped.startswith(f"## {kw}"):
                    capture = True
                    break
            
            if capture:
                section_lines.append(line)
            
            # Stop at next section
            if capture and line.strip().startswith("## ") and not any(kw in line.lower() for kw in keywords):
                break
        
        if not section_lines:
            # Fallback: first 5 non-header lines
            for line in lines[:10]:
                if line.strip() and not line.strip().startswith("#"):
                    section_lines.append(line)
        
        result = "\n".join(section_lines[:20]) if section_lines else "Not specified in source content."
        # Limit each section
        if len(result) > 1000:
            result = result[:1000] + "\n\n[... truncated ...]"
        return result or "Not specified."