title: RegenTribes Gherkin Specs
description: Living specifications in Gherkin BDD format
theme: minima
plugins: []
github:
  repository_url: https://github.com/regentribes/genesis-zero-bot-spec

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - _site/
  - .github/
  - build.py
  - "*.feature"
